### ISSUE TITLE
Heavy user on your tool for 2.8 sprytile

### ISSUE THREAD

**Issue by CheedoCreations** [ologon/Sprytile#4]
I use sprytile alot for 2.8 and i have this annoying constant issue where my texture pallet goes away and doesn't come back when i switch to another material of another texture tile pallet other than that the plugin crashes my blender when im normally trying to build stuff in blender, what can i do to send logs or some kind of information? really really irritated my pallet goes away and theres nothing to get it back other than restarting blender which is obviously time consuming because im using the first 2.8 instead of 2.81 or 2.82 so i would like the plugin to be also compatible with those blender versions because it gives me a traceback error whenever i try putting them into 2.81 which is the version im currently using for other stuff other than 2.8 sprytile

**Comment by ologon** [comment]
Hi! Thanks for using the plugin.
Regarding the tile palette disappearing, long story short, this is due to the object not having the material you have selected. (Sprytile shows all the materials you have added so far, even those your object doesn't have). 

Long story:
For example, let's say you start working on Object A and add a tileset A to it. Sprytile will add a material for it and assign it to Object A. Then you start working on Object B and add another tileset B to it. Now sprytile will show both tileset A and tileset B in the selection menu, however Object A only has a material for tileset A while Object B only has a material for tileset B. So if you work on Object B and select tileset A, the tile palette will not show up.

This also happens in the original sprytile for 2.7, which just showed a black tile palette in this case.

To solve this, you have to manually add the desired material to the object as I explained here:
https://itch.io/post/1158224

It would be nice to have sprytile adding the material automatically when you start using it, however that's what it is now. :)

Regarding crashes, open the windows command prompt and start blender from there (by typing for example "C:\Program Files\Blender Foundation\Blender\blender.exe" then enter) . When sprytile/blender crashes the error causing the crash should remain in the command prompt. Can you tell me what you are getting? (Also knowing when it happens would be helpful)

**Comment by CheedoCreations** [comment]
Surely will respond with more information when a next crash happens, it's been a while since i last crashed because im starting to learn from it but i will add here if something happens next
