### ISSUE TITLE
Tilesets visible across all objects, not just objects that have the tileset as a material.

### ISSUE THREAD

**Issue by vulture-boy** [ologon/Sprytile#9]
At the moment, if you add a tileset to one object and another tileset to another object, both tilesets will be visible regardless of the object you are focused on in the hierarchy. In order to add an existing tileset to an object, you need to add it as a new material to an object. It would be convenient to be able to hide inaccessible tilesets for a particular object so that they do not clutter the selectable tilesets for a given object.

**Comment by ologon** [comment]
Showing all the tilemaps is how sprytile normally works. I agree it can be inconvenient because currently you have to manually add the tilemap you are trying to use to the object materials in case it doesn't have it yet. The best approach would probably be to make this happen automatically when you start using the tilemap, but unfortunately I didn't have the time to implement it. (See here on how to manually add the materials: https://itch.io/post/1158224)

**Comment by vulture-boy** [comment]
Yep, manually adding them works and that's how I've been doing it!

I just don't think I need to see all the tilesets when my objects only use some of them ;)

**Comment by ologon** [comment]
The beta11 I just released introduces a bunch of improvements in this area. Sprytile will now handle adding absent materials for you, so no need to do it manually. And among the filtering options (which were already there but not functional before this release, like they weren't in the original sprytile) there's now an option to only show the materials added to the selected object, which is what you were asking for. (Default is off, because old sprytile users probably expect to see all the scene materials as usual)
![Capture](https://user-images.githubusercontent.com/30046703/83938631-34162b80-a811-11ea-9618-f5788cd62cfc.PNG)

Enjoy!
